// Generated by CoffeeScript 1.4.0
(function() {
  var exec;

  exec = require('child_process').exec;

  module.exports = {
    extract: function(path, destPath, time, size, callback) {
      if (time == null) {
        time = '00:00:01';
      }
      if (size == null) {
        size = '200x125';
      }
      return exec('ffmpeg  -i ' + path + ' -ss ' + time + ' -an -s ' + size + ' -f image2 ' + destPath, function() {
        if (callback) {
          return callback();
        }
      });
    }
  };

}).call(this);
